### PR TITLE
[App -> View] Add animated login screen background

### PR DESCRIPTION
**Pull request by Pdawg-bytes**
Simply updating the client login screen to have a simple animation.

### CODE REVIEW

**Comment by AestheticalZ** [comment]
I'd say a slower and more subtle animation would be nicer.

**Review by AestheticalZ — CHANGES_REQUESTED** [review]
Please remove the changes done to the project files, they're not needed for your changes.

**Comment by Pdawg-bytes** [comment]
I can't build the app unless I do. You should remove the certificate for now so that others can build it without creating a new one.

**Comment by Pdawg-bytes** [comment]
I fixed the csproj files and reverted the SDK versions.

**Review by AestheticalZ — APPROVED** [review]
LGTM

**Pull request merged**
